#ifdef MOUSEKEY_MOVE_DELTA
   #undef MOUSEKEY_MOVE_DELTA
   #define MOUSEKEY_MOVE_DELTA 1
#endif

#ifdef MOUSEKEY_TIME_TO_MAX
   #undef MOUSEKEY_TIME_TO_MAX
   #define MOUSEKEY_TIME_TO_MAX 35 
#endif

#ifdef MOUSEKEY_MAX_SPEED
   #undef MOUSEKEY_MAX_SPEED
   #define MOUSEKEY_MAX_SPEED 25
#endif 

#ifdef MOUSEKEY_WHEEL_DELAY
   #undef MOUSEKEY_WHEEL_DELAY
   #define MOUSEKEY_WHEEL_DELAY 0
#endif 