// #define MK_KINETIC_SPEED 100
#define MOUSEKEY_INTERVAL 10
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 400